# Generated by Django 5.0.6 on 2024-09-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('random_key', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='true', max_length=5)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_picture/')),
                ('about', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
