# Generated by Django 5.0.6 on 2024-09-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_community_communitymembers_messages_topics_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.CharField(default='true', max_length=5),
        ),
    ]
