# Generated by Django 5.0.6 on 2024-09-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0005_conversation_message_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic_link',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
